name: 'Build and package extension'
on:
    push:
        branches:
            - main
        tags:
            - 'v*'

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: false

jobs:
    build:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Cache pnpm modules
              uses: actions/cache@v4
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-

            - uses: pnpm/action-setup@v4
              with:
                  version: latest
                  run_install: true

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  cache: 'pnpm'

            - name: Build the extension
              run: |
                  pnpm build --target=firefox
                  pnpm build --target=chrome

            - name: Package the extension into a zip artifact
              run: |
                  pnpm package --target=firefox
                  pnpm package --target=chrome

            - name: Rename the artifacts
              run: |
                  mv ./build/firefox-prod.zip ./build/shittruyen-bypass-firefox.zip
                  mv ./build/chrome-prod.zip ./build/shittruyen-bypass-chrome.zip

            - name: Upload the artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: shittruyen-bypass
                  path: ./build/*.zip
